[package]
authors = ["Miguel Rodríguez Pérez <miguel@det.uvigo.gal>"]
name = "fastgridcache"
version = "0.1.0"
edition = "2021"

[dependencies]
clap = { version = "3.1.6", features = ["derive", "wrap_help"] }
exitcode = "1.1.2"
itertools = "0.10.3"
num = "0.4.0"
rayon = "1.5.1"
